### ISSUE TITLE
請問之後會考慮開放給"非"校友的開發者使用嗎? 如果會， 那會不會有安全性這方面的疑慮呢?

### ISSUE THREAD

**Issue by WenYuChen** [NCU-CC/ama#6]

**Comment by yyc1217** [comment]
因為才剛開始，安全性我們都是放在第一個也是最重要的考量點，包括將程式碼開放出來給大家檢驗。  
但因為這是台灣第一所學校這樣做，並沒有先例可以參考，所以也希望中央大學的開發者多多關注，讓我們可以提供更安全的服務。  
校外部分我們評估沒有問題的話，就會立即開放。
