### ISSUE TITLE
校園資料是否分散各處室，及其取得之方法

### ISSUE THREAD

**Issue by leVirve** [NCU-CC/ama#7]
請問 API 所開放的資料，原先是否歸各處室所管轄（eg.各處室公告及學生課程等資訊），並且如何由計中統一取得呢？

**Comment by leVirve** [comment]
#3 
Ok, I  see. The problem is duplicate.

**Comment by yyc1217** [comment]
目前api資料來源大致有三個部份：
- 計中負責維護的其他單位的資料庫（如課程資料
- 自行收集的資料（如校內景點
- 民間業者的網頁（如客運業者的網頁

供您參考~

**Comment by leVirve** [comment]
Thank you!
